# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello from RowSQL!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  backend-build:
    desc: build backend application
    cmds:
      - go build -o bin/rowsql ./cmd/server
  frontend-build:
    desc: build frontend application
    cmds:
      - cd ./frontend && pnpm run build

  backend-dev:
    desc: run backend server in development mode
    cmds:
      - air -c air.toml

  frontend-dev:
    desc: run frontend server in development mode
    cmds:
      - cd ./frontend/ && pnpm run dev

  frontend-dev-with-delay:
    desc: run frontend server in development mode with delay
    cmds:
      - echo "waiting for 5 seconds"
      - sleep 5
      - task: frontend-dev

  dev:
    desc: Run the application in development mode
    deps: [backend-dev, frontend-dev-with-delay]
    cmds:
      - echo "Done!"

  build:
    desc: build frontend and backend
    deps: [backend-build, frontend-build]
    cmds:
      - echo "build was successfull"

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./bin/rowsql
  doc:
    desc: generate documentation
    cmds:
      - swag init -g ./cmd/server/main.go -o ./cmd/server/docs
  test:
    desc: test the application
    cmds:
      - go test ./... -failfast
