// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createNewTable, deleteRow, deleteTable, insertOrUpdateRow, listColumns, listHistory, listRecentHistory, listRows, listTables, newTableFormFileds, type Options, rowInsertOrUpdateForm, runSqlQuery } from '../sdk.gen';
import type { CreateNewTableData, CreateNewTableError, CreateNewTableResponse, DeleteRowData, DeleteRowError, DeleteRowResponse, DeleteTableData, DeleteTableError, DeleteTableResponse, InsertOrUpdateRowData, InsertOrUpdateRowError, InsertOrUpdateRowResponse, ListColumnsData, ListColumnsError, ListColumnsResponse, ListHistoryData, ListHistoryError, ListHistoryResponse, ListRecentHistoryData, ListRecentHistoryError, ListRecentHistoryResponse, ListRowsData, ListRowsError, ListRowsResponse2, ListTablesData, ListTablesError, ListTablesResponse, NewTableFormFiledsData, NewTableFormFiledsError, NewTableFormFiledsResponse, RowInsertOrUpdateFormData, RowInsertOrUpdateFormError, RowInsertOrUpdateFormResponse, RunSqlQueryData, RunSqlQueryError, RunSqlQueryResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listHistoryQueryKey = (options?: Options<ListHistoryData>) => createQueryKey('listHistory', options);

/**
 * List query history
 */
export const listHistoryOptions = (options?: Options<ListHistoryData>) => queryOptions<ListHistoryResponse, ListHistoryError, ListHistoryResponse, ReturnType<typeof listHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listHistoryQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listHistoryInfiniteQueryKey = (options?: Options<ListHistoryData>): QueryKey<Options<ListHistoryData>> => createQueryKey('listHistory', options, true);

/**
 * List query history
 */
export const listHistoryInfiniteOptions = (options?: Options<ListHistoryData>) => infiniteQueryOptions<ListHistoryResponse, ListHistoryError, InfiniteData<ListHistoryResponse>, QueryKey<Options<ListHistoryData>>, number | Pick<QueryKey<Options<ListHistoryData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListHistoryData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listHistory({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listHistoryInfiniteQueryKey(options)
});

export const listRecentHistoryQueryKey = (options?: Options<ListRecentHistoryData>) => createQueryKey('listRecentHistory', options);

/**
 * List recent history
 */
export const listRecentHistoryOptions = (options?: Options<ListRecentHistoryData>) => queryOptions<ListRecentHistoryResponse, ListRecentHistoryError, ListRecentHistoryResponse, ReturnType<typeof listRecentHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRecentHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRecentHistoryQueryKey(options)
});

/**
 * Run SQL query
 */
export const runSqlQueryMutation = (options?: Partial<Options<RunSqlQueryData>>): UseMutationOptions<RunSqlQueryResponse, RunSqlQueryError, Options<RunSqlQueryData>> => {
    const mutationOptions: UseMutationOptions<RunSqlQueryResponse, RunSqlQueryError, Options<RunSqlQueryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await runSqlQuery({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a table
 */
export const deleteTableMutation = (options?: Partial<Options<DeleteTableData>>): UseMutationOptions<DeleteTableResponse, DeleteTableError, Options<DeleteTableData>> => {
    const mutationOptions: UseMutationOptions<DeleteTableResponse, DeleteTableError, Options<DeleteTableData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTable({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listTablesQueryKey = (options?: Options<ListTablesData>) => createQueryKey('listTables', options);

/**
 * List of all tables
 */
export const listTablesOptions = (options?: Options<ListTablesData>) => queryOptions<ListTablesResponse, ListTablesError, ListTablesResponse, ReturnType<typeof listTablesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTables({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTablesQueryKey(options)
});

export const newTableFormFiledsQueryKey = (options?: Options<NewTableFormFiledsData>) => createQueryKey('newTableFormFileds', options);

/**
 * Get data types for new table form
 */
export const newTableFormFiledsOptions = (options?: Options<NewTableFormFiledsData>) => queryOptions<NewTableFormFiledsResponse, NewTableFormFiledsError, NewTableFormFiledsResponse, ReturnType<typeof newTableFormFiledsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await newTableFormFileds({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: newTableFormFiledsQueryKey(options)
});

/**
 * Create a new table
 */
export const createNewTableMutation = (options?: Partial<Options<CreateNewTableData>>): UseMutationOptions<CreateNewTableResponse, CreateNewTableError, Options<CreateNewTableData>> => {
    const mutationOptions: UseMutationOptions<CreateNewTableResponse, CreateNewTableError, Options<CreateNewTableData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createNewTable({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRowsQueryKey = (options: Options<ListRowsData>) => createQueryKey('listRows', options);

/**
 * List rows of a table
 */
export const listRowsOptions = (options: Options<ListRowsData>) => queryOptions<ListRowsResponse2, ListRowsError, ListRowsResponse2, ReturnType<typeof listRowsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRows({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRowsQueryKey(options)
});

export const listRowsInfiniteQueryKey = (options: Options<ListRowsData>): QueryKey<Options<ListRowsData>> => createQueryKey('listRows', options, true);

/**
 * List rows of a table
 */
export const listRowsInfiniteOptions = (options: Options<ListRowsData>) => infiniteQueryOptions<ListRowsResponse2, ListRowsError, InfiniteData<ListRowsResponse2>, QueryKey<Options<ListRowsData>>, number | Pick<QueryKey<Options<ListRowsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListRowsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listRows({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRowsInfiniteQueryKey(options)
});

export const listColumnsQueryKey = (options: Options<ListColumnsData>) => createQueryKey('listColumns', options);

/**
 * List columns of a table
 */
export const listColumnsOptions = (options: Options<ListColumnsData>) => queryOptions<ListColumnsResponse, ListColumnsError, ListColumnsResponse, ReturnType<typeof listColumnsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listColumns({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listColumnsQueryKey(options)
});

export const rowInsertOrUpdateFormQueryKey = (options: Options<RowInsertOrUpdateFormData>) => createQueryKey('rowInsertOrUpdateForm', options);

/**
 * Get row insert/update form metadata
 */
export const rowInsertOrUpdateFormOptions = (options: Options<RowInsertOrUpdateFormData>) => queryOptions<RowInsertOrUpdateFormResponse, RowInsertOrUpdateFormError, RowInsertOrUpdateFormResponse, ReturnType<typeof rowInsertOrUpdateFormQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await rowInsertOrUpdateForm({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rowInsertOrUpdateFormQueryKey(options)
});

export const rowInsertOrUpdateFormInfiniteQueryKey = (options: Options<RowInsertOrUpdateFormData>): QueryKey<Options<RowInsertOrUpdateFormData>> => createQueryKey('rowInsertOrUpdateForm', options, true);

/**
 * Get row insert/update form metadata
 */
export const rowInsertOrUpdateFormInfiniteOptions = (options: Options<RowInsertOrUpdateFormData>) => infiniteQueryOptions<RowInsertOrUpdateFormResponse, RowInsertOrUpdateFormError, InfiniteData<RowInsertOrUpdateFormResponse>, QueryKey<Options<RowInsertOrUpdateFormData>>, number | Pick<QueryKey<Options<RowInsertOrUpdateFormData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<RowInsertOrUpdateFormData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await rowInsertOrUpdateForm({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rowInsertOrUpdateFormInfiniteQueryKey(options)
});

/**
 * Insert or update a row
 */
export const insertOrUpdateRowMutation = (options?: Partial<Options<InsertOrUpdateRowData>>): UseMutationOptions<InsertOrUpdateRowResponse, InsertOrUpdateRowError, Options<InsertOrUpdateRowData>> => {
    const mutationOptions: UseMutationOptions<InsertOrUpdateRowResponse, InsertOrUpdateRowError, Options<InsertOrUpdateRowData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await insertOrUpdateRow({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a row
 */
export const deleteRowMutation = (options?: Partial<Options<DeleteRowData>>): UseMutationOptions<DeleteRowResponse, DeleteRowError, Options<DeleteRowData>> => {
    const mutationOptions: UseMutationOptions<DeleteRowResponse, DeleteRowError, Options<DeleteRowData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRow({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
