// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateNewTableData, CreateNewTableErrors, CreateNewTableResponses, DeleteRowData, DeleteRowErrors, DeleteRowResponses, DeleteTableData, DeleteTableErrors, DeleteTableResponses, InsertOrUpdateRowData, InsertOrUpdateRowErrors, InsertOrUpdateRowResponses, ListColumnsData, ListColumnsErrors, ListColumnsResponses, ListHistoryData, ListHistoryErrors, ListHistoryResponses, ListRecentHistoryData, ListRecentHistoryErrors, ListRecentHistoryResponses, ListRowsData, ListRowsErrors, ListRowsResponses, ListTablesData, ListTablesErrors, ListTablesResponses, NewTableFormFiledsData, NewTableFormFiledsErrors, NewTableFormFiledsResponses, RowInsertOrUpdateFormData, RowInsertOrUpdateFormErrors, RowInsertOrUpdateFormResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List query history
 */
export const listHistory = <ThrowOnError extends boolean = false>(options?: Options<ListHistoryData, ThrowOnError>) => (options?.client ?? client).get<ListHistoryResponses, ListHistoryErrors, ThrowOnError>({ url: '/api/v1/history', ...options });

/**
 * List recent history
 */
export const listRecentHistory = <ThrowOnError extends boolean = false>(options?: Options<ListRecentHistoryData, ThrowOnError>) => (options?.client ?? client).get<ListRecentHistoryResponses, ListRecentHistoryErrors, ThrowOnError>({ url: '/api/v1/history/recent', ...options });

/**
 * Delete a table
 */
export const deleteTable = <ThrowOnError extends boolean = false>(options: Options<DeleteTableData, ThrowOnError>) => (options.client ?? client).delete<DeleteTableResponses, DeleteTableErrors, ThrowOnError>({
    url: '/api/v1/tables',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List of all tables
 */
export const listTables = <ThrowOnError extends boolean = false>(options?: Options<ListTablesData, ThrowOnError>) => (options?.client ?? client).get<ListTablesResponses, ListTablesErrors, ThrowOnError>({ url: '/api/v1/tables', ...options });

/**
 * Get data types for new table form
 */
export const newTableFormFileds = <ThrowOnError extends boolean = false>(options?: Options<NewTableFormFiledsData, ThrowOnError>) => (options?.client ?? client).get<NewTableFormFiledsResponses, NewTableFormFiledsErrors, ThrowOnError>({ url: '/api/v1/tables/form/new', ...options });

/**
 * Create a new table
 */
export const createNewTable = <ThrowOnError extends boolean = false>(options: Options<CreateNewTableData, ThrowOnError>) => (options.client ?? client).post<CreateNewTableResponses, CreateNewTableErrors, ThrowOnError>({
    url: '/api/v1/tables/form/new',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List rows of a table
 */
export const listRows = <ThrowOnError extends boolean = false>(options: Options<ListRowsData, ThrowOnError>) => (options.client ?? client).get<ListRowsResponses, ListRowsErrors, ThrowOnError>({ url: '/api/v1/tables/{tableName}', ...options });

/**
 * List columns of a table
 */
export const listColumns = <ThrowOnError extends boolean = false>(options: Options<ListColumnsData, ThrowOnError>) => (options.client ?? client).get<ListColumnsResponses, ListColumnsErrors, ThrowOnError>({ url: '/api/v1/tables/{tableName}/columns', ...options });

/**
 * Get row insert/update form metadata
 */
export const rowInsertOrUpdateForm = <ThrowOnError extends boolean = false>(options: Options<RowInsertOrUpdateFormData, ThrowOnError>) => (options.client ?? client).get<RowInsertOrUpdateFormResponses, RowInsertOrUpdateFormErrors, ThrowOnError>({ url: '/api/v1/tables/{tableName}/form', ...options });

/**
 * Insert or update a row
 */
export const insertOrUpdateRow = <ThrowOnError extends boolean = false>(options: Options<InsertOrUpdateRowData, ThrowOnError>) => (options.client ?? client).post<InsertOrUpdateRowResponses, InsertOrUpdateRowErrors, ThrowOnError>({
    url: '/api/v1/tables/{tableName}/form',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a row
 */
export const deleteRow = <ThrowOnError extends boolean = false>(options: Options<DeleteRowData, ThrowOnError>) => (options.client ?? client).delete<DeleteRowResponses, DeleteRowErrors, ThrowOnError>({ url: '/api/v1/tables/{tableName}/row/{hash}', ...options });
