// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type ColMetaData = {
    colName: string;
    hasAutoIncrement: boolean;
    hasDefault: unknown;
    hasDigit?: boolean;
    hasSize: boolean;
    hasValues?: boolean;
    isUnique: boolean;
    type: string;
};

export type ColValue = {
    colName: string;
    defaultValue?: unknown;
    hasAutoIncrement: boolean;
    hasDefault: unknown;
    hasDigit?: boolean;
    hasSize: boolean;
    hasValues?: boolean;
    isPk: boolean;
    isUnique: boolean;
    type: string;
    value: unknown;
};

export type ColValues = {
    autoIncrement?: boolean;
    colName: string;
    default: unknown;
    isNull: boolean;
    isPk: boolean;
    isUnique: boolean;
    size?: number;
    type: string;
    value: unknown;
};

export type CreeteNewTableInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    inputs: Array<ColValues> | null;
    tableName: string;
};

export type DataRow = {
    hash: string;
    values: Array<unknown> | null;
};

export type DeleteTableRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    tableName: string;
    verificationQuery: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FormDatatype = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    numericType: Array<NumericDataType> | null;
    stringType: Array<StringDataType> | null;
};

export type History = {
    id: number;
    message: string;
    time: string;
};

export type ListRowsResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    activeTable: string;
    cols: Array<ColMetaData> | null;
    hasNextPage: boolean;
    page: number;
    rowCount: number;
    rows: Array<DataRow> | null;
    totalPages: number;
};

export type ListTablesRow = {
    tableName: string;
    tableSchema: string;
};

export type NumericDataType = {
    hasAutoIncrement: boolean;
    hasDigit: boolean;
    hasSize: boolean;
    type: string;
};

export type RowInsertOrUpdateFormOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    cols: Array<ColMetaData> | null;
};

export type StringDataType = {
    hasSize: boolean;
    hasValues: boolean;
    type: string;
};

export type CreeteNewTableInputBodyWritable = {
    inputs: Array<ColValues> | null;
    tableName: string;
};

export type DeleteTableRequestWritable = {
    tableName: string;
    verificationQuery: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FormDatatypeWritable = {
    numericType: Array<NumericDataType> | null;
    stringType: Array<StringDataType> | null;
};

export type ListRowsResponseWritable = {
    activeTable: string;
    cols: Array<ColMetaData> | null;
    hasNextPage: boolean;
    page: number;
    rowCount: number;
    rows: Array<DataRow> | null;
    totalPages: number;
};

export type RowInsertOrUpdateFormOutputBodyWritable = {
    cols: Array<ColMetaData> | null;
};

export type ListHistoryData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
    };
    url: '/api/v1/history';
};

export type ListHistoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListHistoryError = ListHistoryErrors[keyof ListHistoryErrors];

export type ListHistoryResponses = {
    /**
     * OK
     */
    200: Array<History> | null;
};

export type ListHistoryResponse = ListHistoryResponses[keyof ListHistoryResponses];

export type ListRecentHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/history/recent';
};

export type ListRecentHistoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRecentHistoryError = ListRecentHistoryErrors[keyof ListRecentHistoryErrors];

export type ListRecentHistoryResponses = {
    /**
     * OK
     */
    200: Array<History> | null;
};

export type ListRecentHistoryResponse = ListRecentHistoryResponses[keyof ListRecentHistoryResponses];

export type DeleteTableData = {
    body: DeleteTableRequestWritable;
    path?: never;
    query?: never;
    url: '/api/v1/tables';
};

export type DeleteTableErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteTableError = DeleteTableErrors[keyof DeleteTableErrors];

export type DeleteTableResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteTableResponse = DeleteTableResponses[keyof DeleteTableResponses];

export type ListTablesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tables';
};

export type ListTablesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListTablesError = ListTablesErrors[keyof ListTablesErrors];

export type ListTablesResponses = {
    /**
     * OK
     */
    200: Array<ListTablesRow> | null;
};

export type ListTablesResponse = ListTablesResponses[keyof ListTablesResponses];

export type NewTableFormFiledsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tables/form/new';
};

export type NewTableFormFiledsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type NewTableFormFiledsError = NewTableFormFiledsErrors[keyof NewTableFormFiledsErrors];

export type NewTableFormFiledsResponses = {
    /**
     * OK
     */
    200: FormDatatype;
};

export type NewTableFormFiledsResponse = NewTableFormFiledsResponses[keyof NewTableFormFiledsResponses];

export type CreateNewTableData = {
    body: CreeteNewTableInputBodyWritable;
    path?: never;
    query?: never;
    url: '/api/v1/tables/form/new';
};

export type CreateNewTableErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateNewTableError = CreateNewTableErrors[keyof CreateNewTableErrors];

export type CreateNewTableResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CreateNewTableResponse = CreateNewTableResponses[keyof CreateNewTableResponses];

export type ListRowsData = {
    body?: never;
    path: {
        tableName: string;
    };
    query?: {
        page?: number;
        column?: string;
        order?: 'ASC' | 'DESC';
    };
    url: '/api/v1/tables/{tableName}';
};

export type ListRowsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRowsError = ListRowsErrors[keyof ListRowsErrors];

export type ListRowsResponses = {
    /**
     * OK
     */
    200: ListRowsResponse;
};

export type ListRowsResponse2 = ListRowsResponses[keyof ListRowsResponses];

export type ListColumnsData = {
    body?: never;
    path: {
        tableName: string;
    };
    query?: never;
    url: '/api/v1/tables/{tableName}/columns';
};

export type ListColumnsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListColumnsError = ListColumnsErrors[keyof ListColumnsErrors];

export type ListColumnsResponses = {
    /**
     * OK
     */
    200: Array<ColMetaData> | null;
};

export type ListColumnsResponse = ListColumnsResponses[keyof ListColumnsResponses];

export type RowInsertOrUpdateFormData = {
    body?: never;
    path: {
        tableName: string;
    };
    query?: {
        page?: number;
        hash?: string;
    };
    url: '/api/v1/tables/{tableName}/form';
};

export type RowInsertOrUpdateFormErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RowInsertOrUpdateFormError = RowInsertOrUpdateFormErrors[keyof RowInsertOrUpdateFormErrors];

export type RowInsertOrUpdateFormResponses = {
    /**
     * OK
     */
    200: RowInsertOrUpdateFormOutputBody;
};

export type RowInsertOrUpdateFormResponse = RowInsertOrUpdateFormResponses[keyof RowInsertOrUpdateFormResponses];

export type InsertOrUpdateRowData = {
    body: Array<ColValue> | null;
    path: {
        tableName: string;
    };
    query?: {
        hash?: string;
        page?: number;
    };
    url: '/api/v1/tables/{tableName}/form';
};

export type InsertOrUpdateRowErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type InsertOrUpdateRowError = InsertOrUpdateRowErrors[keyof InsertOrUpdateRowErrors];

export type InsertOrUpdateRowResponses = {
    /**
     * No Content
     */
    204: void;
};

export type InsertOrUpdateRowResponse = InsertOrUpdateRowResponses[keyof InsertOrUpdateRowResponses];

export type DeleteRowData = {
    body?: never;
    path: {
        tableName: string;
        hash: string;
    };
    query?: {
        page?: number;
    };
    url: '/api/v1/tables/{tableName}/row/{hash}';
};

export type DeleteRowErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteRowError = DeleteRowErrors[keyof DeleteRowErrors];

export type DeleteRowResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRowResponse = DeleteRowResponses[keyof DeleteRowResponses];
