// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zColType = z.object({
    dataType: z.string(),
    hasAutoIncrement: z.boolean(),
    hasDefault: z.boolean(),
    hasDigit: z.boolean().optional(),
    hasSize: z.boolean(),
    hasValues: z.boolean().optional(),
    inputType: z.enum([
        'text',
        'number',
        'checkbox',
        'textarea',
        'json',
        'select'
    ]),
    isNull: z.boolean(),
    isPk: z.boolean(),
    isUnique: z.boolean()
});

export const zColValue = z.object({
    columnName: z.string(),
    columnType: zColType,
    defaultValue: z.unknown().optional(),
    size: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    value: z.unknown().optional()
});

export const zCreeteNewTableInputBody = z.object({
    $schema: z.url().readonly().optional(),
    inputs: z.array(zColValue).nullable(),
    tableName: z.string()
});

export const zDeleteTableRequest = z.object({
    $schema: z.url().readonly().optional(),
    tableName: z.string(),
    verificationQuery: z.string()
});

export const zErrorDetail = z.object({
    location: z.string().optional(),
    message: z.string().optional(),
    value: z.unknown().optional()
});

export const zErrorModel = z.object({
    $schema: z.url().readonly().optional(),
    detail: z.string().optional(),
    errors: z.array(zErrorDetail).nullish(),
    instance: z.url().optional(),
    status: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    title: z.string().optional(),
    type: z.url().optional().default('about:blank')
});

export const zHistory = z.object({
    id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    message: z.string(),
    time: z.iso.datetime()
});

export const zListTablesRow = z.object({
    tableName: z.string(),
    tableSchema: z.string()
});

export const zRowInsertOrUpdateFormOutputBody = z.object({
    $schema: z.url().readonly().optional(),
    cols: z.array(zColValue).nullable()
});

export const zRowSet = z.object({
    columns: z.array(zColValue).nullable(),
    hash: z.string()
});

export const zListRowsResponse = z.object({
    $schema: z.url().readonly().optional(),
    activeTable: z.string(),
    cols: z.array(zColValue).nullable(),
    hasNextPage: z.boolean(),
    page: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    rowCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    rows: z.array(zRowSet).nullable(),
    totalPages: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zVarianDataType = z.object({
    hasAutoIncrement: z.boolean(),
    hasDigit: z.boolean(),
    hasSize: z.boolean(),
    hasValues: z.boolean(),
    isNumeric: z.boolean(),
    type: z.string()
});

export const zFormDatatype = z.object({
    $schema: z.url().readonly().optional(),
    numericType: z.array(zVarianDataType).nullable(),
    stringType: z.array(zVarianDataType).nullable()
});

export const zCreeteNewTableInputBodyWritable = z.object({
    inputs: z.array(zColValue).nullable(),
    tableName: z.string()
});

export const zDeleteTableRequestWritable = z.object({
    tableName: z.string(),
    verificationQuery: z.string()
});

export const zErrorModelWritable = z.object({
    detail: z.string().optional(),
    errors: z.array(zErrorDetail).nullish(),
    instance: z.url().optional(),
    status: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    title: z.string().optional(),
    type: z.url().optional().default('about:blank')
});

export const zFormDatatypeWritable = z.object({
    numericType: z.array(zVarianDataType).nullable(),
    stringType: z.array(zVarianDataType).nullable()
});

export const zListRowsResponseWritable = z.object({
    activeTable: z.string(),
    cols: z.array(zColValue).nullable(),
    hasNextPage: z.boolean(),
    page: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    rowCount: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    rows: z.array(zRowSet).nullable(),
    totalPages: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zRowInsertOrUpdateFormOutputBodyWritable = z.object({
    cols: z.array(zColValue).nullable()
});

export const zListHistoryQuery = z.object({
    page: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(1))
});

/**
 * OK
 */
export const zListHistoryResponse = z.array(zHistory).nullable();

/**
 * OK
 */
export const zListRecentHistoryResponse = z.array(zHistory).nullable();

export const zDeleteTableBody = zDeleteTableRequestWritable;

/**
 * No Content
 */
export const zDeleteTableResponse = z.void();

/**
 * OK
 */
export const zListTablesResponse = z.array(zListTablesRow).nullable();

/**
 * OK
 */
export const zNewTableFormFiledsResponse = zFormDatatype;

export const zCreateNewTableBody = zCreeteNewTableInputBodyWritable;

/**
 * No Content
 */
export const zCreateNewTableResponse = z.void();

export const zListRowsPath = z.object({
    tableName: z.string()
});

export const zListRowsQuery = z.object({
    page: z.coerce.bigint().gte(BigInt(1)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(1)),
    column: z.string().optional(),
    order: z.enum(['ASC', 'DESC']).optional()
});

/**
 * OK
 */
export const zListRowsResponse2 = zListRowsResponse;

export const zListColumnsPath = z.object({
    tableName: z.string()
});

/**
 * OK
 */
export const zListColumnsResponse = z.array(zColValue).nullable();

export const zRowInsertOrUpdateFormPath = z.object({
    tableName: z.string()
});

export const zRowInsertOrUpdateFormQuery = z.object({
    page: z.coerce.bigint().gte(BigInt(1)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(1)),
    hash: z.string().optional()
});

/**
 * OK
 */
export const zRowInsertOrUpdateFormResponse = zRowInsertOrUpdateFormOutputBody;

export const zInsertOrUpdateRowBody = z.array(zColValue).nullable();

export const zInsertOrUpdateRowPath = z.object({
    tableName: z.string()
});

export const zInsertOrUpdateRowQuery = z.object({
    hash: z.string().optional(),
    page: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(1))
});

/**
 * No Content
 */
export const zInsertOrUpdateRowResponse = z.void();

export const zDeleteRowPath = z.object({
    tableName: z.string(),
    hash: z.string()
});

export const zDeleteRowQuery = z.object({
    page: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional().default(BigInt(1))
});

/**
 * No Content
 */
export const zDeleteRowResponse = z.void();
