name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Run go generate
        run: go generate ./...

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10.1

      - name: Frontend Lint
        working-directory: ./frontend
        run: pnpm lint

  vuln_check:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Prepare embed directory
        run: mkdir -p frontend/dist

      - name: Run Govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Run go generate
        run: go generate ./...

      - name: Run go test
        run: go test ./...

      - name: Build Backend
        run: go build -v -o bin/rowsql ./cmd/server
